import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useState } from "react";

const ProductAnalysis = ({
  onNext,
  onBack,
  setProductData,
}: {
  onNext: () => void;
  onBack: () => void;
  setProductData: (data: {
    companyName: string;
    companyDomain: string;
    companyDescription: string;
  }) => void;
}) => {
  const [companyName, setCompanyName] = useState("");
  const [companyDomain, setCompanyDomain] = useState("");
  const [companyDescription, setCompanyDescription] = useState(
    "Travelcoup specializes in organizing group trips and providing comprehensive travel planning services. Whether you're looking to join a group trip, seek personal travel advice, or explore destinations, Kaijago aims to make travel planning hassle-free and enjoyable..."
  );

  const handleNext = () => {
    setProductData({ companyName, companyDomain, companyDescription });
    onNext();
  };

  return (
    <div className="w-full">
      <h1 className="text-3xl text-left font-bold mb-7">
        Tell us about your business
      </h1>
      <form className="space-y-4">
        <div>
          <Label
            htmlFor="name"
            className="block text-sm text-left font-medium text-gray-700 mb-1"
          >
            Company Name
          </Label>
          <Input
            className="w-full h-[56px] bg-gray-100"
            id="name"
            type="text"
            placeholder="Company name"
            value={companyName}
            onChange={(e) => setCompanyName(e.target.value)}
          />
        </div>
        <div>
          <Label
            htmlFor="domain"
            className="block text-sm text-left font-medium text-gray-700 mb-1"
          >
            Company domain
          </Label>
          <Input
            className="w-full h-[56px] bg-gray-100"
            id="domain"
            type="url"
            placeholder="https://"
            value={companyDomain}
            onChange={(e) => setCompanyDomain(e.target.value)}
          />
        </div>
        <div>
          <Label
            htmlFor="description"
            className="block text-sm text-left font-medium text-gray-700 mb-1"
          >
            Company description
          </Label>
          <Textarea
            id="description"
            placeholder="Autogenerated by AI"
            className="h-40"
            value={companyDescription}
            onChange={(e) => setCompanyDescription(e.target.value)}
          />
          <div className="flex justify-end space-x-2 mt-2">
            <Button variant="outline" size="sm">
              <svg
                className="w-4 h-4 mr-1"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"
                />
              </svg>
              Edit
            </Button>
            <Button variant="outline" size="sm">
              <svg
                className="w-4 h-4 mr-1"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                />
              </svg>
              Regenerate
            </Button>
          </div>
        </div>
        <div className="flex space-x-4">
          <Button
            variant="secondary"
            className="w-full h-12 bg-[#E8E8E8]"
            onClick={onBack}
          >
            Go back
          </Button>
          <Button
            variant="secondary"
            style={{
              background:
                "linear-gradient(0deg, #1D77E1, #2B73C8), linear-gradient(180deg, hsla(0, 0%, 100%, 0.2) 0%, hsla(210, 56%, 48%, 0.2) 100%)",
              border: "transparent",
              borderRadius: "10px",
            }}
            className="text-white w-full h-12"
            onClick={handleNext}
          >
            Continue
          </Button>
        </div>
      </form>
    </div>
  );
};

export default ProductAnalysis;
